8 implementation of users nearby feature
Heroskin12/dinnit pull request #9
Opened 2024-10-30 23:33 UTC by isym444

2024-10-31 06:36 UTC, Heroskin12 commented on dinnit/app/(tabs)/home.jsx
> +            <CirclePlus
All looks good but unsure if a plus circle is best choice here? Suggests adding more but the user can't add more to a 'nearby' section. Maybe a ... instead to suggest see more?

2024-10-31 06:36 UTC, Heroskin12 requested changes
left one comment in home.jsx

2024-10-31 09:37 UTC, isym444 commented on dinnit/app/(tabs)/home.jsx
> +            <CirclePlus
ah cool, happy to add this instead, I was just following the wireframe 🤣. Will make this change to see how it looks and what we prefer :)

2024-11-01 19:17 UTC, Heroskin12 approved these changes
We can later export this to its own component maybe as well to keep the home file leaner. But otherwise all works and looks good.

2024-11-01 19:17 UTC, merged